2019-08-06 06:32:05 DEBUG Starting logging
2019-08-06 06:32:05 ERROR (clsSocketServer.py:137):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-06 06:32:05.888546
2019-08-06 06:32:05 DEBUG Starting logging
2019-08-06 06:32:05 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:32:05.893077
2019-08-06 06:32:19 DEBUG Starting logging
2019-08-06 06:32:19 DEBUG Starting logging
2019-08-06 06:32:19 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:32:19.821590
2019-08-06 06:32:19 ERROR (clsSocketServer.py:137):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-06 06:32:19.817557
2019-08-06 06:34:47 DEBUG Starting logging
2019-08-06 06:34:47 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:34:47.830209
2019-08-06 06:34:47 DEBUG Starting logging
2019-08-06 06:34:47 ERROR (clsSocketServer.py:137):Start():  Event Id : None m: getsockaddrarg: port must be 0-65535.2019-08-06 06:34:47.832983
2019-08-06 06:35:19 DEBUG Starting logging
2019-08-06 06:35:19 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:35:19.221191
2019-08-06 06:37:00 DEBUG Starting logging
2019-08-06 06:37:00 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:37:00.888732
2019-08-06 06:37:25 DEBUG Starting logging
2019-08-06 06:37:25 DEBUG Starting logging
2019-08-06 06:37:25 ERROR (clsSocketServer.py:202):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 06:37:25.262485
2019-08-06 06:37:25 ERROR (clsSocketServer.py:202):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 06:37:25.263330
2019-08-06 06:37:54 DEBUG Starting logging
2019-08-06 06:37:54 DEBUG Starting logging
2019-08-06 06:37:54 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:37:54.745576
2019-08-06 06:37:54 ERROR (clsSocketServer.py:137):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-06 06:37:54.748998
2019-08-06 06:39:34 DEBUG Starting logging
2019-08-06 06:39:34 ERROR (clsSocketServer.py:218):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:39:34.158629
2019-08-06 06:49:10 DEBUG Starting logging
2019-08-06 06:49:10 ERROR (clsSocketServer.py:219):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:49:10.176303
2019-08-06 06:51:06 DEBUG Starting logging
2019-08-06 06:51:06 ERROR (clsSocketServer.py:220):send():  Event Id : None m: 'NoneType' object has no attribute 'send'2019-08-06 06:51:06.201870
2019-08-06 07:18:18 DEBUG Starting logging
2019-08-06 07:18:18 DEBUG Starting logging
2019-08-06 07:18:18 ERROR (clsSocketServer.py:204):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 07:18:18.959690
2019-08-06 07:18:18 ERROR (clsSocketServer.py:204):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 07:18:18.965129
2019-08-06 07:21:16 DEBUG Starting logging
2019-08-06 07:21:16 ERROR (clsSocketServer.py:204):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 07:21:16.717237
2019-08-06 07:24:36 DEBUG Starting logging
2019-08-06 07:24:36 ERROR (clsSocketServer.py:204):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 07:24:36.708305
2019-08-06 07:24:36 DEBUG Starting logging
2019-08-06 07:24:36 ERROR (clsSocketServer.py:204):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-06 07:24:36.712007
